### ISSUE TITLE
YARA rule generator

### ISSUE THREAD

**Issue by geekscrapy** [securisec/chepy_plugins#2]
Generate yara rules for the data in state

Discuss requirements!
Do we have a template rule?
Detect based on the state, as hex chars, string...?

**Comment by securisec** [comment]
This idea, you @geekscrapy is more knowledgeable than i am. I am not even sure where to start, but the two next plugin ideas i have are for yara rules, and git dirs. I am very open to exploring your ideas for yara rules and how they can be structured so that it can be consistently applied to any data type.
